import logging
from typing import Dict, Any

from app.schemas.agents import DocumentationAgentInput

logger = logging.getLogger(__name__)

class DocumentationAgent:
    def __init__(self):
        self.name = "Documentation Agent"

    async def execute(self, run_id: str, all_artifacts: Dict[str, Any]) -> Dict[str, Any]:
        logger.info(f"Executing Documentation Agent for run {run_id}")
        return {
            "run_id": run_id,
            "docs": {
                "readme": "markdown_string",
                "api_docs": "markdown_string"
            }
        }


async def run_documentation_agent(input_data: DocumentationAgentInput | Dict[str, Any]) -> Dict[str, Any]:
    """Workflow entrypoint for Documentation Agent."""
    if isinstance(input_data, dict):
        input_data = DocumentationAgentInput.model_validate(input_data)

    run_id = str(input_data.run_id)
    project_title = input_data.prd.product_vision.elevator_pitch
    devops_ready = input_data.devops_output is not None

    return {
        "run_id": run_id,
        "documents": {
            "README.md": f"# {project_title}\n\nAutogenerated project summary.",
            "API_REFERENCE.md": "# API Reference\n\nSee /api/v1/runs endpoints.",
            "ARCHITECTURE.md": "# Architecture\n\nFastAPI + Celery + Redis + Next.js.",
            "KNOWN_ISSUES.md": (
                "# Known Issues\n\n"
                + ("No critical issues in this generated run." if devops_ready else "DevOps output was not available when docs were generated.")
            ),
            "CONTRIBUTING.md": "# Contributing\n\nUse feature branches and PR reviews.",
            "CHANGELOG.md": "# Changelog\n\n- Initial generated release",
        },
    }
