import logging
from typing import Dict, Any

from app.schemas.agents import DocumentationAgentInput

logger = logging.getLogger(__name__)


def _build_known_issues_markdown(qa_output: Any) -> str:
    bugs = list(getattr(qa_output, "bugs", []) or [])
    if not bugs:
        return "# Known Issues\n\nNo open QA issues were reported for this run."

    severity_rank = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    sorted_bugs = sorted(
        bugs,
        key=lambda bug: (
            severity_rank.get(getattr(getattr(bug, "severity", None), "value", "low"), 9),
            getattr(bug, "bug_id", ""),
        ),
    )

    lines = ["# Known Issues", "", "The following issues were identified by the QA Agent:", ""]
    for bug in sorted_bugs:
        severity = getattr(getattr(bug, "severity", None), "value", "low")
        owner = getattr(getattr(bug, "fix_owner", None), "value", "developer")
        suggested_fix = getattr(bug, "suggested_fix", None) or "No fix suggestion provided."
        lines.extend(
            [
                f"## {getattr(bug, 'bug_id', 'BUG')} — {getattr(bug, 'title', 'Issue')}",
                f"- Severity: {severity.upper()}",
                f"- Owner: {owner}",
                f"- Affected File: {getattr(bug, 'affected_file', 'unknown')}",
                f"- Description: {getattr(bug, 'description', 'No description')}",
                f"- Fix Instruction: {suggested_fix}",
                "",
            ]
        )

    return "\n".join(lines).strip()

class DocumentationAgent:
    def __init__(self):
        self.name = "Documentation Agent"

    async def execute(self, run_id: str, all_artifacts: Dict[str, Any]) -> Dict[str, Any]:
        logger.info(f"Executing Documentation Agent for run {run_id}")
        return {
            "run_id": run_id,
            "docs": {
                "readme": "markdown_string",
                "api_docs": "markdown_string"
            }
        }


async def run_documentation_agent(input_data: DocumentationAgentInput | Dict[str, Any]) -> Dict[str, Any]:
    """Workflow entrypoint for Documentation Agent."""
    if isinstance(input_data, dict):
        input_data = DocumentationAgentInput.model_validate(input_data)

    run_id = str(input_data.run_id)
    project_title = input_data.prd.product_vision.elevator_pitch
    known_issues_md = _build_known_issues_markdown(input_data.qa_output)

    return {
        "run_id": run_id,
        "documents": {
            "README.md": f"# {project_title}\n\nAutogenerated project summary.",
            "API_REFERENCE.md": "# API Reference\n\nSee /api/v1/runs endpoints.",
            "ARCHITECTURE.md": "# Architecture\n\nFastAPI + Celery + Redis + Next.js.",
            "KNOWN_ISSUES.md": known_issues_md,
            "CONTRIBUTING.md": "# Contributing\n\nUse feature branches and PR reviews.",
            "CHANGELOG.md": "# Changelog\n\n- Initial generated release",
        },
    }
